"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mq^)s17tg#3a-_71%g5f0shnl7)xqruz733t0=uo&81w1x9d3q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'demo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

from kombu import Queue
from celery.schedules import crontab

CELERY_QUEUES = (
    Queue('dealers', routing_key='dealers'),
)
SELLER_TP_FLAG_QUEUE = "dev-gupta"

CACHES = {
    "default": {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': [
            'redis://localhost:6379?db=8'
        ],
        'TIMEOUT': 60 * 60 * 2,  # Cache timeout as 2 hours
        'OPTIONS': {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "CONNECTION_POOL_KWARGS": {"max_connections": 2000}
        },
    },
}


CELERY_ROUTES = {
    # Add task routes here. Use celery for default queue and routing_key
    'demo.tasks.generate_report_task': {
        'queue': 'dealers',
        'routing_key': 'dealers'
    },
}
EMTEX_RABBITMQ = {
    'HOST': '172.31.44.180',
    'USER': 'loctite',
    'PASSWORD': 'loctite',
}

# Overridden Celery config setting



CMS_RABBITMQ_SETTINGS = {
    'HOST': 'localhost',
    'USER': 'guest',
    'PASSWORD': 'guest',
    'PORT': 5672
}
BROKER_URL = 'amqp://{user}:{password}@{host}//'.format(
    user=CMS_RABBITMQ_SETTINGS['USER'], password=CMS_RABBITMQ_SETTINGS['PASSWORD'], host=CMS_RABBITMQ_SETTINGS['HOST']
)
RMQ_QUEUE = {
    "ORDER_SYNC_QUEUE": {
        "queue_name": "dev-gupta",
        "exchange_name": "rishabh-order-exchange",
        "key_name": "marketplace-order-key",
        "consumer_name": "order_sync_queue_consumer"
    },
}
CELERYBEAT_SCHEDULE = {
    'generate_report_task': {
        'task': 'demo.tasks.generate_report_task',
        'schedule': crontab(minute='*/1'),
    },
}    

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
SALES_FORCE_ORDER_EXCHANGE = 'rishabh-order-exchang'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
